spring:
  datasource:
    url: jdbc:mysql://146.56.130.214:3306/maroonest?characterEncoding=utf8
    username: maroonest
    password: Vkfkrhs8985!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo123
  mapper-locations: mybatis/mapper/**/*.xml